FROM node:20-alpine
  
  WORKDIR /app
  
  COPY package*.json ./
  
  RUN npm install
  
  COPY . .
  
  EXPOSE 5173
  
  CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

#   docker build -f Dockerfile.dev -t vue-app-dev .

#   docker run -d \                                
#   --name vue-frontend-dev \
#   -p 5173:5173 \
#   -v $(pwd):/app \
#   -v /app/node_modules \
#   vue-app-dev